import type { Metadata } from "next";
import { montserrat } from "@/app/ui/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Players",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}>{children}</body>
    </html>
  );
}
